#!/usr/bin/env bash

docker-compose up -d --build

#docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=kafka],SCRAM-SHA-512=[password=kafka]' --entity-type users --entity-name kafka

#docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=alice-secret],SCRAM-SHA-512=[password=alice-secret]' --entity-type users --entity-name alice
#docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=bob-secret],SCRAM-SHA-512=[password=bob-secret]' --entity-type users --entity-name bob


docker-compose exec kafka kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add --cluster --operation=All --allow-principal=User:kafka

# Allow Streams to read the input topics:
docker-compose exec kafka kafka-acls -authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:alice --operation Read --topic source-topic
docker-compose exec kafka kafka-acls -authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:alice --operation Describe --topic source-topic
## only necessary to debug and play with the app using the kafka-console
docker-compose exec kafka kafka-acls -authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:alice --operation Write --topic source-topic

# Allow Streams to write to the output topics:
docker-compose exec kafka kafka-acls -authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:alice --operation Write --topic target-topic
docker-compose exec kafka kafka-acls -authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:alice --operation Describe --topic source-topic
## only necessary to debug and play with the app
docker-compose exec kafka kafka-acls -authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:alice --operation Read --topic target-topic --group '*'

# Allow Streams to manage its own internal topics and consumer groups:
docker-compose exec kafka kafka-acls -authorizer-properties zookeeper.connect=zookeeper:2181 --add --allow-principal User:alice --operation All --resource-pattern-type prefixed --topic porsche-streams-app --group porsche-streams-app

docker-compose exec kafka kafka-topics --create --topic source-topic --zookeeper zookeeper:2181 --partitions 3 --replication-factor 1
docker-compose exec kafka kafka-topics --create --topic target-topic --zookeeper zookeeper:2181 --partitions 3 --replication-factor 1

echo "Example configuration:"
echo "Should succeed (alice authorized)"
echo "-> docker-compose exec kafka kafka-console-producer --broker-list kafka:9092 --topic target-topic --producer.config=/etc/kafka/alice.properties"
echo "Should fail (bob is NOT authorized)"
echo "-> docker-compose exec kafka kafka-console-producer --broker-list kafka:9092 --topic target-topic --producer.config=/etc/kafka/bob.properties"
